package br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "manutencao_cobranca_bancaria", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.gov.caixa.sibar.ObjectFactory.class,
    br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto.ObjectFactory.class,
    br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto.externo.ObjectFactory.class
})
public interface ManutencaoCobrancaBancaria {

    /**
     *
     * @param parameters
     * @return returns
     * br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto.SERVICOSAIDANEGOCIALTYPE
     */
    @WebMethod(operationName = "INCLUI_BOLETO", action = "IncluiBoleto")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", partName = "parameters")
    public SERVICOSAIDANEGOCIALTYPE incluiBOLETO(
            @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", partName = "parameters") SERVICOENTRADANEGOCIALTYPE parameters);

    /**
     *
     * @param parameters
     * @return returns
     * br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto.SERVICOSAIDANEGOCIALTYPE
     */
    @WebMethod(operationName = "BAIXA_BOLETO", action = "BaixaBoleto")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", partName = "parameters")
    public SERVICOSAIDANEGOCIALTYPE baixaBOLETO(
            @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", partName = "parameters") SERVICOENTRADANEGOCIALTYPE parameters);

    /**
     *
     * @param parameters
     * @return returns
     * br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto.SERVICOSAIDANEGOCIALTYPE
     */
    @WebMethod(operationName = "ALTERA_BOLETO", action = "AlteraBoleto")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", partName = "parameters")
    public SERVICOSAIDANEGOCIALTYPE alteraBOLETO(
            @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", partName = "parameters") SERVICOENTRADANEGOCIALTYPE parameters);

}
