package br.gov.caixa.sibar.manutencao_cobranca_bancaria.boleto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "manutencao_cobranca_bancaria", targetNamespace = "http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", wsdlLocation = "https://des.barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto?wsdl")
public class ManutencaoCobrancaBancaria_Service extends Service {

    private final static URL MANUTENCAOCOBRANCABANCARIA_WSDL_LOCATION;
    private final static WebServiceException MANUTENCAOCOBRANCABANCARIA_EXCEPTION;
    private final static QName MANUTENCAOCOBRANCABANCARIA_QNAME = new QName("http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", "manutencao_cobranca_bancaria");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            /**
             * Para Ambrinete de Producao, remover o início 'des.' da URL. Fica
             * assim:
             * https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto?wsdl
             */
            url = new URL("https://des.barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANUTENCAOCOBRANCABANCARIA_WSDL_LOCATION = url;
        MANUTENCAOCOBRANCABANCARIA_EXCEPTION = e;
    }

    public ManutencaoCobrancaBancaria_Service() {
        super(__getWsdlLocation(), MANUTENCAOCOBRANCABANCARIA_QNAME);
    }

    public ManutencaoCobrancaBancaria_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANUTENCAOCOBRANCABANCARIA_QNAME, features);
    }

    public ManutencaoCobrancaBancaria_Service(URL wsdlLocation) {
        super(wsdlLocation, MANUTENCAOCOBRANCABANCARIA_QNAME);
    }

    public ManutencaoCobrancaBancaria_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANUTENCAOCOBRANCABANCARIA_QNAME, features);
    }

    public ManutencaoCobrancaBancaria_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManutencaoCobrancaBancaria_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns ManutencaoCobrancaBancaria
     */
    @WebEndpoint(name = "manutencao_cobranca_bancariaSOAP")
    public ManutencaoCobrancaBancaria getManutencaoCobrancaBancariaSOAP() {
        return super.getPort(new QName("http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", "manutencao_cobranca_bancariaSOAP"), ManutencaoCobrancaBancaria.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns ManutencaoCobrancaBancaria
     */
    @WebEndpoint(name = "manutencao_cobranca_bancariaSOAP")
    public ManutencaoCobrancaBancaria getManutencaoCobrancaBancariaSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://caixa.gov.br/sibar/manutencao_cobranca_bancaria/boleto", "manutencao_cobranca_bancariaSOAP"), ManutencaoCobrancaBancaria.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANUTENCAOCOBRANCABANCARIA_EXCEPTION != null) {
            throw MANUTENCAOCOBRANCABANCARIA_EXCEPTION;
        }
        return MANUTENCAOCOBRANCABANCARIA_WSDL_LOCATION;
    }
}
